name: github-demo
on: [push]
jobs:
  job-name:
    runs-on: [self-hosted, test, Linux]
    steps:
      - run:  echo "Deploying application...."
      - run:  pwd
      - run:  whoami
      - run:  cd /githubaction
      - run:  ./CI-CD_github.sh
      - run:  echo "Application successfully deployed."
