name: github-demo
on: [push]
# defaults:
#       run:
#         working-directory: ./githubaction
jobs:
  job-name:
    runs-on: [self-hosted, test, Linux]
    steps:
      - uses: actions/checkout@v2
      - run:  echo "Deploying application...."
      - run:  pwd
      - run:  whoami
      # - run:  touch text.txt
      # - run:  ./github.sh
      - run:  sudo cd /githubaction
      - run:  pwd
      - run:  touch text.txt
      - run:  pwd
      # - run:  ./CI-CD_github.sh
      - run:  echo "Application successfully deployed."
