name: github-demo
on: [push]
# defaults:
#       run:
#         working-directory: /githubaction
jobs:
  job-name:
           runs-on: [self-hosted, test, Linux]
           steps:
             - uses: actions/checkout@v3
      #   with:
      #    path: ./../../../../githubaction
      # - run:
      #     working-directory: /githubaction
             - run:  echo "Deploying application....."
             - run:  pwd
             - run:  whoami
             - run:  chmod +x CI-CD.sh
             - run:  ./CI-CD.sh
             - run:  echo "script completed"
             - run:  echo "Application successfully deployed."
                 
               
             
