name: github-demo
on: [push]
jobs:
  job-name:
    runs-on: [self-hosted, test, Linux]
    defaults:
      run:
        working-directory: ./githubaction
    steps:
      - run:  echo "Deploying application...."
      - run:  pwd
      - run:  whoami
   #   - run:  cd /githubaction
   #   - run:  pwd
      - run:  ./CI-CD_github.sh
      - run:  echo "Application successfully deployed."
