name: github-demo
on: [push]
# defaults:
#       run:
#         working-directory: /githubaction
jobs:
  job-name:
    runs-on: [self-hosted, test, Linux]
    steps:
      # - uses: actions/checkout@v3
      #   with:
      #    path: ./../../../../githubaction
      # - run:
      #     working-directory: /githubaction
      - run:  echo "Deploying application....."
      - run:  pwd
      - run:  whoami
      - run:  sudo ./text.sh
      # - run:  touch text.txt
      # - run:  ./github.sh
      # - run:  sh cd /githubaction
      # - run:  pwd
      # - run:  touch text.txt
      # - run:  pwd
      # - run:  ./CI-CD_github.sh
      - run:  echo "Application successfully deployed."
